### ISSUE TITLE
ArgumentError: nil can't be converted to a Time value

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#103]
Sentry:

```
ArgumentError: nil can't be converted to a Time value
  from action_view/helpers/date_helper.rb:697:in `normalize_distance_of_time_argument_to_time'
  from action_view/helpers/date_helper.rb:100:in `distance_of_time_in_words'
  from action_view/helpers/date_helper.rb:177:in `time_ago_in_words'
  from sixnines.rb:275:in `block (3 levels) in <top (required)>'
  from objects/endpoint.rb:170:in `ping'
  from objects/base.rb:54:in `block in ping'
  from objects/base.rb:54:in `map'
  from objects/base.rb:54:in `ping'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.6`

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#103` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
