### ISSUE TITLE
decoding error

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#111]
```
GLogin::Codec::DecodingError: GLogin::Codec::DecodingError
  from glogin/codec.rb:50:in `decrypt'
  from glogin/cookie.rb:57:in `to_user'
  from sixnines.rb:110:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:1040:in `block in process_route'
  from sinatra/base.rb:1038:in `catch'
  from sinatra/base.rb:1038:in `process_route'
  from sinatra/base.rb:983:in `block in filter!'
  from sinatra/base.rb:983:in `each'
  from sinatra/base.rb:983:in `filter!'
  from sinatra/base.rb:1096:in `block in dispatch!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:1094:in `dispatch!'
  from sinatra/base.rb:924:in `block in call!'
  from sinatra/base.rb:1076:in `block in invoke'
  from sinatra/base.rb:1076:in `catch'
  from sinatra/base.rb:1076:in `invoke'
  from sinatra/base.rb:924:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/ssl.rb:27:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1957:in `call'
  from sinatra/base.rb:1502:in `block in call'
  from sinatra/base.rb:1729:in `synchronize'
  from sinatra/base.rb:1502:in `call'
  from rack/handler/webrick.rb:86:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:307:in `block in start_thread'

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.13`

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#111` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
