### ISSUE TITLE
email subscribe to endpoints

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#22]
A user should be able to subscribe to any endpoint and receive emails when the status changes. By default endpoint owner must be subscribed.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 1cbcae0 2017-08-11T07:54:51
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:yegor256/sixnines#22` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$3.call(Unknown Source)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm....
```

**Comment by yegor256** [comment]
There are other systems for that, e.g. statuscake.com
