### ISSUE TITLE
undefined method `>' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#75]
```
NoMethodError: undefined method `>' for nil:NilClass
  from action_view/helpers/date_helper.rb:100:in `distance_of_time_in_words'
  from /app/views/index.haml:27:in `block (2 levels) in singleton class'
  from /app/views/index.haml:22:in `each'
  from /app/views/index.haml:22:in `block in singleton class'
  from tilt/template.rb:170:in `call'
  from tilt/template.rb:170:in `evaluate'
  from tilt/haml.rb:19:in `evaluate'
  from tilt/template.rb:109:in `render'
  from sinatra/base.rb:823:in `render'
  from sinatra/base.rb:677:in `haml'
  from /app/sixnines.rb:139:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@0crat assign @pdacostaporto

**Comment by 0crat** [comment]
> @0crat assign @pdacostaporto ([here](https://github.com/yegor256/sixnines/issues/75#issuecomment-319074306))

@yegor256 Job `gh:yegor256/sixnines#75` assigned to @pdacostaporto, please go ahead.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+720](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
@rultor please, ask @yegor256 to close this issue and [read more](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html)

**Comment by pdacostaporto** [comment]
@yegor256 should this be closed or did I miss something?

**Comment by yegor256** [comment]
@pdacostaporto when you finish/fix the bug/ticket, please post a message to the ticket author (myself in this case) that it has to be closed.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#75` is now out of scope.

**Comment by yegor256** [comment]
@pdacostaporto and many thanks for your help! :)

**Comment by 0crat** [comment]
+30 points just awarded to @pdacostaporto, total is [+75](http://www.0crat.com/u/pdacostaporto).

**Comment by pdacostaporto** [comment]
@yegor256 you're welcome. I'm open for new tasks if needed.
