### ISSUE TITLE
Timeout::Error: execution expired

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#76]
```
Timeout::Error: execution expired
  from net/protocol.rb:158:in `wait_readable'
  from net/protocol.rb:158:in `rbuf_fill'
  from net/protocol.rb:136:in `readuntil'
  from net/protocol.rb:146:in `readline'
  from net/http/response.rb:40:in `read_status_line'
  from net/http/response.rb:29:in `read_new'
  from seahorse/client/net_http/patches.rb:29:in `block in new_transport_request'
  from seahorse/client/net_http/patches.rb:26:in `catch'
  from seahorse/client/net_http/patches.rb:26:in `new_transport_request'
  from net/http.rb:1407:in `request'
  from net/http.rb:1400:in `block in request'
  from net/http.rb:853:in `start'
  from net/http.rb:1398:in `request'
  from /app/objects/resource.rb:47:in `block in take'
  from timeout.rb:106:in `timeout'
  from /app/objects/resource.rb:46:in `take'
  from /app/objects/proxied_resource.rb:42:in `block in take'
  from /app/objects/proxied_resource.rb:40:in `each'
  from /app/objects/proxied_resource.rb:40:in `take'
  from /app/objects/endpoint.rb:114:in `ping'
  from /app/objects/base.rb:54:in `block in ping'
  from /app/objects/base.rb:54:in `map'
  from /app/objects/base.rb:54:in `ping'
  from /app/sixnines.rb:279:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from /app/sixnines.rb:276:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@0crat assign @pdacostaporto

**Comment by 0crat** [comment]
> @0crat assign @pdacostaporto ([here](https://github.com/yegor256/sixnines/issues/76#issuecomment-319074365))

@yegor256 Job `gh:yegor256/sixnines#76` assigned to @pdacostaporto, please go ahead.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+735](http://www.0crat.com/u/yegor256).

**Comment by pdacostaporto** [comment]
@yegor256 what is Resourse.take supposed to do on timeout?

**Comment by yegor256** [comment]
@pdacostaporto I guess it should return something like:

```ruby
[500, '', "took too long: 5.2s"]
```

**Comment by 0crat** [comment]
@rultor please, ask @yegor256 to close this issue and [read more](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html)

**Comment by pdacostaporto** [comment]
@yegor256 same here, did I miss something?

**Comment by pdacostaporto** [comment]
@yegor256 please close this one too if you think it's done.

**Comment by yegor256** [comment]
@pdacostaporto thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.1`

**Comment by 0crat** [comment]
@pdacostaporto this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#76`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#76` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#76` is not assigned to anyone.
