### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#77]
```
TypeError: no implicit conversion of nil into String
  from /app/objects/cookie.rb:63:in `update'
  from /app/objects/cookie.rb:63:in `to_s'
  from /app/sixnines.rb:122:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@0crat assign @pdacostaporto

**Comment by 0crat** [comment]
> @0crat assign @pdacostaporto ([here](https://github.com/yegor256/sixnines/issues/77#issuecomment-321802386))

@yegor256 Job `gh:yegor256/sixnines#77` assigned to @pdacostaporto, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1530](http://www.0crat.com/u/yegor256).

**Comment by pdacostaporto** [comment]
@yegor256 looks like some problem with cookies. I would like log in to my development instance but sign-in option gives me [404](https://github.com/login/oauth/authorize?client_id=test&redirect_uri=http://www.sixnines.io/oauth). How do you simulate login?

**Comment by yegor256** [comment]
@pdacostaporto see aa3fe89

**Comment by pdacostaporto** [comment]
@yegor256 thanks!

**Comment by 0crat** [comment]
@pdacostaporto this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#77`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#77` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#77` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#77` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#77` is not assigned to anyone.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#77` assigned to @pdacostaporto, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#77`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#77` assigned to @pdacostaporto. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#77`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#77` assigned to @pdacostaporto  ([profile](http://www.0crat.com/u/pdacostaporto})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.
