### ISSUE TITLE
Errno::ENETUNREACH: Network is unreachable

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#81]
There some other issue in production:

```
Errno::ENETUNREACH: Network is unreachable - connect(2) for "www.microsoft.com" port 443
  from net/http.rb:880:in `initialize'
  from net/http.rb:880:in `open'
  from net/http.rb:880:in `block in connect'
  from timeout.rb:91:in `block in timeout'
  from timeout.rb:101:in `timeout'
  from net/http.rb:878:in `connect'
  from net/http.rb:863:in `do_start'
  from net/http.rb:852:in `start'
  from net/http.rb:1398:in `request'
  from /app/objects/resource.rb:47:in `block in take'
  from timeout.rb:91:in `block in timeout'
  from timeout.rb:33:in `block in catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:106:in `timeout'
  from /app/objects/resource.rb:46:in `take'
  from /app/objects/proxied_resource.rb:42:in `block in take'
  from /app/objects/proxied_resource.rb:40:in `each'
  from /app/objects/proxied_resource.rb:40:in `take'
  from /app/objects/endpoint.rb:114:in `ping'
  from /app/objects/base.rb:54:in `block in ping'
  from /app/objects/base.rb:54:in `map'
  from /app/objects/base.rb:54:in `ping'
  from /app/sixnines.rb:279:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from /app/sixnines.rb:276:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
Errno::ENETUNREACH: Failed to open TCP connection to www.microsoft.com:443 (Network is unreachable - connect(2) for "www.microsoft.com" port 443)
  from net/http.rb:882:in `rescue in block in connect'
  from net/http.rb:879:in `block in connect'
  from timeout.rb:91:in `block in timeout'
  from timeout.rb:101:in `timeout'
  from net/http.rb:878:in `connect'
  from net/http.rb:863:in `do_start'
  from net/http.rb:852:in `start'
  from net/http.rb:1398:in `request'
  from /app/objects/resource.rb:47:in `block in take'
  from timeout.rb:91:in `block in timeout'
  from timeout.rb:33:in `block in catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:106:in `timeout'
  from /app/objects/resource.rb:46:in `take'
  from /app/objects/proxied_resource.rb:42:in `block in take'
  from /app/objects/proxied_resource.rb:40:in `each'
  from /app/objects/proxied_resource.rb:40:in `take'
  from /app/objects/endpoint.rb:114:in `ping'
  from /app/objects/base.rb:54:in `block in ping'
  from /app/objects/base.rb:54:in `map'
  from /app/objects/base.rb:54:in `ping'
  from /app/sixnines.rb:279:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from /app/sixnines.rb:276:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@0crat assign @pdacostaporto

**Comment by 0crat** [comment]
> @0crat assign @pdacostaporto ([here](https://github.com/yegor256/sixnines/issues/81#issuecomment-321804077))

@yegor256 Job `gh:yegor256/sixnines#81` assigned to @pdacostaporto, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1545](http://www.0crat.com/u/yegor256).

**Comment by pdacostaporto** [comment]
@yegor256 should this be another 500 code case?

**Comment by yegor256** [comment]
@pdacostaporto yes, sure, but with a new custom message, I guess.

**Comment by pdacostaporto** [comment]
@yegor256 check #86

**Comment by pdacostaporto** [comment]
@yegor256 close this if you think it's done

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#81` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @pdacostaporto, total is [+195](http://www.0crat.com/u/pdacostaporto).
