### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#88]
```
Errno::ECONNRESET: Connection reset by peer - SSL_connect
  from net/http.rb:933:in `connect_nonblock'
  from net/http.rb:933:in `connect'
  from net/http.rb:863:in `do_start'
  from net/http.rb:852:in `start'
  from net/http.rb:1398:in `request'
  from /app/objects/http_response.rb:35:in `receive'
  from /app/objects/checked_response.rb:36:in `receive'
  from /app/objects/checks/network_unreachable_response.rb:31:in `check'
  from /app/objects/checked_response.rb:38:in `receive'
  from /app/objects/checks/timedout_response.rb:35:in `block in check'
  from timeout.rb:91:in `block in timeout'
  from timeout.rb:33:in `block in catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:106:in `timeout'
  from /app/objects/checks/timedout_response.rb:35:in `check'
  from /app/objects/checked_response.rb:38:in `receive'
  from /app/objects/checks/socket_error_response.rb:35:in `check'
  from /app/objects/checked_response.rb:38:in `receive'
  from /app/objects/checks/proxy_authentication_required_response.rb:31:in `check'
  from /app/objects/checked_response.rb:38:in `receive'
  from /app/objects/checks/zlib_buffer_error_response.rb:31:in `check'
  from /app/objects/checked_response.rb:38:in `receive'
  from /app/objects/resource.rb:58:in `take'
  from /app/objects/counted_resource.rb:39:in `take'
  from /app/objects/proxied_resource.rb:42:in `block in take'
  from /app/objects/proxied_resource.rb:40:in `each'
  from /app/objects/proxied_resource.rb:40:in `take'
  from /app/objects/endpoint.rb:122:in `ping'
  from /app/objects/base.rb:54:in `block in ping'
  from /app/objects/base.rb:54:in `map'
  from /app/objects/base.rb:54:in `ping'
  from /app/sixnines.rb:277:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from /app/sixnines.rb:274:in `block in <top (required)>'
  from sinatra/base.rb:1611:in `call'
  from sinatra/base.rb:1611:in `block in compile!'
  from sinatra/base.rb:975:in `block (3 levels) in route!'
  from sinatra/base.rb:994:in `route_eval'
  from sinatra/base.rb:975:in `block (2 levels) in route!'
  from sinatra/base.rb:1015:in `block in process_route'
  from sinatra/base.rb:1013:in `catch'
  from sinatra/base.rb:1013:in `process_route'
  from sinatra/base.rb:973:in `block in route!'
  from sinatra/base.rb:972:in `each'
  from sinatra/base.rb:972:in `route!'
  from sinatra/base.rb:1085:in `block in dispatch!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:1082:in `dispatch!'
  from sinatra/base.rb:907:in `block in call!'
  from sinatra/base.rb:1067:in `block in invoke'
  from sinatra/base.rb:1067:in `catch'
  from sinatra/base.rb:1067:in `invoke'
  from sinatra/base.rb:907:in `call!'
  from sinatra/base.rb:895:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:18:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/base.rb:49:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from sinatra/base.rb:212:in `call'
  from rack/head.rb:13:in `call'
  from rack/methodoverride.rb:22:in `call'
  from sinatra/base.rb:182:in `call'
  from sinatra/base.rb:2013:in `call'
  from sinatra/base.rb:1487:in `block in call'
  from sinatra/base.rb:1787:in `synchronize'
  from sinatra/base.rb:1487:in `call'
  from rack/handler/webrick.rb:88:in `service'
  from webrick/httpserver.rb:140:in `service'
  from webrick/httpserver.rb:96:in `run'
  from webrick/server.rb:296:in `block in start_thread'
```

**Comment by yegor256** [comment]
@0crat assign @pdacostaporto

**Comment by 0crat** [comment]
> @0crat assign @pdacostaporto  ([here](https://github.com/yegor256/sixnines/issues/88#issuecomment-324823487))

@yegor256 Job `gh:yegor256/sixnines#88` assigned to @pdacostaporto, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2295](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#88`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#88` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#88` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#88` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#88` is not assigned to anyone.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#88` assigned to @pdacostaporto, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#88`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#88` assigned to @pdacostaporto. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/sixnines/issues/88#issuecomment-497197692))

@yegor256 Job `gh:yegor256/sixnines#88` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#88` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#88](https://github.com/yegor256/sixnines/issues/88) is now out of scope
