### ISSUE TITLE
FrozenError: can't modify frozen String

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#97]
```
FrozenError: can't modify frozen String
  from sixnines.rb:286:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from sixnines.rb:265:in `block in <top (required)>'
  from sinatra/base.rb:1635:in `call'
  from sinatra/base.rb:1635:in `block in compile!'
  from sinatra/base.rb:992:in `block (3 levels) in route!'
  from sinatra/base.rb:1011:in `route_eval'
  from sinatra/base.rb:992:in `block (2 levels) in route!'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.1`

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#97` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
