### ISSUE TITLE
Twitter::Error::Unauthorized: Could not authenticate you.

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#98]
```
Twitter::Error::Unauthorized: Could not authenticate you.
  from twitter/rest/request.rb:81:in `fail_or_return_response_body'
  from twitter/rest/request.rb:39:in `perform'
  from twitter/rest/utils.rb:50:in `perform_request'
  from twitter/rest/utils.rb:72:in `perform_request_with_object'
  from twitter/rest/utils.rb:64:in `perform_post_with_object'
  from twitter/rest/tweets.rb:155:in `update!'
  from twitter/rest/tweets.rb:126:in `update'
  from sixnines.rb:278:in `block (3 levels) in <top (required)>'
  from objects/endpoint.rb:170:in `ping'
  from objects/base.rb:54:in `block in ping'
  from objects/base.rb:54:in `map'
  from objects/base.rb:54:in `ping'
  from sixnines.rb:268:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from sixnines.rb:265:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.2`

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#98` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
