### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect SYSCALL

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#99]
```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
  from net/protocol.rb:44:in `connect_nonblock'
  from net/protocol.rb:44:in `ssl_socket_connect'
  from net/http.rb:996:in `connect'
  from net/http.rb:930:in `do_start'
  from net/http.rb:919:in `start'
  from net/http.rb:1470:in `request'
  from objects/http_response.rb:35:in `receive'
  from objects/checked_response.rb:36:in `receive'
  from objects/checks/network_unreachable_response.rb:31:in `check'
  from objects/checked_response.rb:38:in `receive'
  from objects/checks/timedout_response.rb:35:in `block in check'
  from timeout.rb:93:in `block in timeout'
  from timeout.rb:33:in `block in catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:33:in `catch'
  from timeout.rb:108:in `timeout'
  from objects/checks/timedout_response.rb:35:in `check'
  from objects/checked_response.rb:38:in `receive'
  from objects/checks/socket_error_response.rb:35:in `check'
  from objects/checked_response.rb:38:in `receive'
  from objects/checks/zlib_buffer_error_response.rb:31:in `check'
  from objects/checked_response.rb:38:in `receive'
  from objects/resource.rb:57:in `take'
  from objects/counted_resource.rb:39:in `take'
  from objects/proxied_resource.rb:43:in `block in take'
  from objects/proxied_resource.rb:40:in `each'
  from objects/proxied_resource.rb:40:in `take'
  from objects/endpoint.rb:122:in `ping'
  from objects/base.rb:54:in `block in ping'
  from objects/base.rb:54:in `map'
  from objects/base.rb:54:in `ping'
  from sixnines.rb:268:in `block (2 levels) in <top (required)>'
  from open-uri.rb:37:in `open'
  from open-uri.rb:37:in `open'
  from sixnines.rb:265:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.3`

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.3`

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#99` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
